//
//  SignupViewController.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright © 2021 VDOTOK. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignupViewController: UIViewController {
    
    // MARK: - Outlets
   @IBOutlet weak var userNameTF: UITextField!
   @IBOutlet weak var emailTF: UITextField!
   @IBOutlet weak var passwordTF: UITextField!
    
    // MARK: - Public properties -
    
    var presenter: SignupPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        bindPresenter()
    }
    
    @IBAction func didTapLogin(_ sender: UIButton) {
        presenter.login()
    }
    
    @IBAction func didTapSignup(_ sender: UIButton) {
        guard let userName = userNameTF.text,
              let email = emailTF.text,
              let password = passwordTF.text
        else {return}
        presenter.signup(with: userName, email: email, password: password)
    }
    
    private func bindPresenter() {
        presenter.output = { output in
            switch output {
            case .showLoading:
                ProgressHud.show(viewController: self)
            case .hideLoading:
                ProgressHud.hide()
            case .show(let error):
                ProgressHud.showError(message: error, viewController: self)
            }
        }
    }
}

// MARK: - Extensions -

extension SignupViewController: SignupViewInterface {
    
}
