//
//  SignupViewController.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SignupViewController: UIViewController {
    
    // MARK: - Outlets
    weak var userNameTF: UITextField!
    weak var emailTF: UITextField!
    weak var passwordTF: UITextField!
    
    // MARK: - Public properties -
    
    var presenter: SignupPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func didTapLogin(_ sender: UIButton) {
        presenter.login()
    }
    
    @IBAction func didTapSignup(_ sender: UIButton) {
        guard let userName = userNameTF.text,
              let email = emailTF.text,
              let password = passwordTF.text
        else {return}
        presenter.signup(with: userName, email: email, password: password)
    }
    
}

// MARK: - Extensions -

extension SignupViewController: SignupViewInterface {
    
}
