//
//  SignupInteractor.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SignupInteractor : BaseDataStore {
    
    let translator: ObjectTranslator
    
    init(service: Service, translator: ObjectTranslator = ObjectTranslation()) {
        self.translator = translator
        super.init(service: service)
    }
    
}

// MARK: - Extensions -

extension SignupInteractor: SignupInteractorInterface {
    
    func singup(with request: SignupRequest, complition: @escaping SignupComplition) {
        service.post(request: request) { result in
            switch result {
            case .success(let data):
                self.translate(data: data, complition: complition)
            case .failure(let error):
                complition(.failure(error))
            }
        }
    }
    
    private func translate(data: Data, complition: loginComplition) {
        do {
            let response: UserResponse = try translator.decodeObject(data: data)
            switch response.status {
            case 200:
                VDOTOKObject<UserResponse>().setData(response)
                VDOTOKObject<String>().setToken(response.authToken)
                
            default:
                break
            }
            complition(.success(response))
        }
        catch {
            complition(.failure(error))
        }
    }
}
