//
//  CallingInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CallingWireframeInterface: WireframeInterface {
}

protocol CallingViewInterface: ViewInterface {
}

protocol CallingPresenterInterface: PresenterInterface {
}

protocol CallingInteractorInterface: InteractorInterface {
}
