//
//  CallingInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import iOSSDKStreaming


typealias CallingOutput = (CallingPresenter.Output) -> Void

protocol CallingWireframeInterface: WireframeInterface {
    func moveToCalling(sdk: VTokSDK, particinats: [Participant], users: [User], sessionDirection: SessionDirection)
    func moveToIncomingCall(sdk: VTokSDK, baseSession: VTokBaseSession, users: [User],sessionDirection: SessionDirection)
    func moveToAudio(sdk: VTokSDK, participants: [Participant], users: [User],sessionDirection: SessionDirection)
}

protocol CallingViewInterface: ViewInterface {
}

protocol CallingPresenterInterface: PresenterInterface {
    
    var users: [User]? {get set}
    var output: CallingOutput? {get set}
    var session: VTokBaseSession? {get set}
    func viewModelDidLoad()
    func viewModelWillAppear()
    func viewModelDidDisapper()
    func acceptCall(session: VTokBaseSession)
    func rejectCall(session: VTokBaseSession)
    func hangupCall(session: VTokBaseSession)
    func flipCamera(session: VTokBaseSession, state: CameraType)
    func mute(session: VTokBaseSession, state: AudioState)
    func speaker(session: VTokBaseSession, state: SpeakerState)
    func disableVideo(session: VTokBaseSession, state: VideoState)
}

protocol CallingInteractorInterface: InteractorInterface {
}
