//
//  CallingInteractor.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright © 2021 VDOTOK. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CallingInteractor {
}

// MARK: - Extensions -

extension CallingInteractor: CallingInteractorInterface {
}
