//
//  ChannelWireframe.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import iOSSDKConnect
import iOSSDKStreaming

final class ChannelWireframe: BaseWireframe<ChannelViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Channel", bundle: nil)

    // MARK: - Module setup -
    let interactor = ChannelInteractor()
    init(broadCastData: BroadcastData? = nil) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ChannelViewController.self)
        super.init(viewController: moduleViewController)

        
        let presenter = ChannelPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        presenter.interactor?.presenter = presenter
    }

}

// MARK: - Extensions -

extension ChannelWireframe: ChannelWireframeInterface {
 
    
    func moveToCalling(particinats: [Participant], users: [User], sdk: VTokSDK, broadCastData: BroadcastData?, screenType: ScreenType = .videoView) {
        let frame = CallingWireframe(vtokSdk: sdk, participants: particinats, screenType: screenType, contact: users, broadCastData: broadCastData)
        navigationController?.viewControllers.last?.presentWireframe(frame)
    }
    
    func moveToIncomingCall(sdk: VTokSDK, baseSession: VTokBaseSession, users: [User]) {
        let frame = CallingWireframe(vtokSdk: sdk, participants: nil, screenType: .incomingCall, session: baseSession, contact: users)
        navigationController?.presentWireframe(frame)
    }
    
    func moveToAudio(sdk: VTokSDK, participants: [Participant], users: [User]) {
        let frame = CallingWireframe(vtokSdk: sdk, participants: participants, screenType: .audioView, contact: users)
        navigationController?.presentWireframe(frame)
    }
    
    func move(to: ChannelNavigationOptions,client: ChatClient, group: Group?, user: UserResponse, messages: [ChatMessage]) {
        switch to {
        case .chat:
            guard let group = group else {return}
            navigationController?.pushWireframe(ChatWireframe(client: client, group: group, user: user, messages: messages))
        case .broadcastOverlay:
            let vc = BroadcastOverlay()
            vc.modalPresentationStyle = .custom
            vc.modalTransitionStyle = .crossDissolve
            vc.delegate = self
            navigationController?.present(vc, animated: true, completion: nil)
        }
    }
    
    func moveToCreateGroup(client: ChatClient) {
        
        let frame = ContactWireframe(client: client)
        navigationController?.pushWireframe(frame)
    }
    
    func dismissView() {
        navigationController?.dismiss(animated: true, completion: {
    
        })
    }
    
}

extension ChannelWireframe: BroadcastOverlayDelegate {
    func moveToCallingView(broadcastData: BroadcastData) {
        interactor.moveToCallingView(broadcastData: broadcastData)
    }
    
    func didUpdate(broadcastData: BroadcastData) {
        interactor.broadCastData = broadcastData
    }
    
    
}
