//
//  ChannelInteractor.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChannelInteractor: BaseDataStore {
    
    let translator: ObjectTranslator
    
     init(service: Service, translator: ObjectTranslator = ObjectTranslation()) {
        self.translator = translator
        super.init(service: service)
    }
}

// MARK: - Extensions -

extension ChannelInteractor: ChannelInteractorInterface {
    func fetchGroups(complition: @escaping ChannelComplition) {
       let request = AllGroupRequest()
        service.get(request: request) { [weak self] result in
            guard let self = self else {return}
            switch result {
            case .success(let data):
                self.translation(with: data, complitionHandler: complition)
            case .failure(let error):
                complition(.failure(error))
            }
        }
    }
    
    private func translation(with data: Data, complitionHandler: ChannelComplition) {
        do {
            let response: GroupResponse = try translator.decodeObject(data: data)
            complitionHandler(.success(response))
        } catch {
            complitionHandler(.failure(error))
        }
    }
    
}
