//
//  ChannelInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import iOSSDKConnect
import iOSSDKStreaming

enum ChannelNavigationOptions {
    case chat
}



typealias ChannelOutput = (ChannelPresenter.Output) -> Void

typealias ChannelComplition = ((Result<GroupResponse, Error>) -> Void)

protocol ChannelWireframeInterface: WireframeInterface {
    func move(to: ChannelNavigationOptions,client: ChatClient, group: Group, user: UserResponse, messages: [ChatMessage])
    func moveToCreateGroup(client: ChatClient)
    func moveToCalling(sdk: VTokSDK, particinats: [Participant], users: [User])
    func moveToIncomingCall(sdk: VTokSDK, baseSession: VTokBaseSession, users: [User])
    func moveToAudio(sdk: VTokSDK, participants: [Participant], users: [User])
}

protocol ChannelViewInterface: ViewInterface {
}

protocol ChannelPresenterInterface: PresenterInterface {
    var channelOutput: ChannelOutput? {get set}
    var isSearching: Bool {get set }
    var messages: [String: [ChatMessage]] {get set}
    var groups: [Group]  {get set}
    var unreadMessages:[String:[ChatMessage]] {get set}
    func fetchGroups()
    func viewDidLoad()
    func viewWillAppear()
    func itemAt(row: Int) -> TempGroup?
    func channelsCount() -> Int
    func logout()
    func navigation(to: ChannelNavigationOptions, messages: [ChatMessage], group: Group)
    func moveToCreateGroup()
   

    
}

protocol ChannelInteractorInterface: InteractorInterface {
    
    func fetchGroups(complition: @escaping ChannelComplition)
    func fetchUsers(complition: @escaping AllUserComplition)
}
