//
//  ChannelInteractor.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChannelInteractor {
}

// MARK: - Extensions -

extension ChannelInteractor: ChannelInteractorInterface {
}
