//
//  ChannelInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias ChannelOutput = (ChannelPresenter.Output) -> Void

typealias ChannelComplition = ((Result<GroupResponse, Error>) -> Void)

protocol ChannelWireframeInterface: WireframeInterface {
}

protocol ChannelViewInterface: ViewInterface {
}

protocol ChannelPresenterInterface: PresenterInterface {
    var channelOutput: ChannelOutput? {get set}
    func fetchGroups()
    func viewDidLoad()
    func viewWillAppear()
    func itemAt(row: Int) -> TempGroup?
    func channelsCount() -> Int
    var isSearching: Bool {get set }
    
}

protocol ChannelInteractorInterface: InteractorInterface {
    
    func fetchGroups(complition: @escaping ChannelComplition)
}
