//
//  ContactInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 01/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import iOSSDKConnect
typealias ContactOutput = (ContactPresenter.Output) -> Void

protocol ContactWireframeInterface: WireframeInterface {
}

protocol ContactViewInterface: ViewInterface {
}

protocol ContactPresenterInterface: PresenterInterface {
    var output: ContactOutput? { get set}
    var contacts: [User] {get set}
    var searchContacts: [User] {get set}
    var isSearching: Bool {get set}
    var client: ChatClient? {get set}
    func viewModelDidLoad()
    func viewModelWillAppear()
    func rowsCount() -> Int
    func viewModelItem(row: Int) -> User
    func filterGroups(with text: String)
    func createGroup(with user: User)
}

protocol ContactInteractorInterface: InteractorInterface {
}
