//
//  ChatInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 01/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias ChatOutput = (ChatPresenter.Output) -> Void

protocol ChatWireframeInterface: WireframeInterface {
}

protocol ChatViewInterface: ViewInterface {
    
}

protocol ChatPresenterInterface: PresenterInterface {
    var group: Group {get set}
    var messages: [ChatMessage] {get set}
    var user: UserResponse {get set}
    var chatOutput: ChatOutput? {get set}
    func dispatchPackage(start: Bool)
    func sendMessage(text: String)
    func messageCount() -> Int
    func itemAt(row: Int) -> (ChatMessage,CellType)
    func receivedMessage(userInfo: [String: AnyObject])
    func sendSeenMessage(message: ChatMessage, row: Int)
}

protocol ChatInteractorInterface: InteractorInterface {
}
