//
//  ChatPresenter.swift
//  IOS-combine
//
//  Created by usama farooq on 01/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import iOSSDKConnect

final class ChatPresenter {

    // MARK: - Private properties -

    private unowned let view: ChatViewInterface
    private let interactor: ChatInteractorInterface
    private let wireframe: ChatWireframeInterface
    var mqtt: ChatClient
    var group: Group
    var messages: [ChatMessage] = []
    var user: UserResponse

    // MARK: - Lifecycle -

    init(
        view: ChatViewInterface,
        interactor: ChatInteractorInterface,
        wireframe: ChatWireframeInterface,
        client: ChatClient,
        group: Group,
        user: UserResponse,
        messages: [ChatMessage]
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.mqtt = client
        self.group = group
        self.messages = messages
        self.user = user
    }
}

// MARK: - Extensions -

extension ChatPresenter: ChatPresenterInterface {
}
