//
//  LoginInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias loginComplition = ((Result<UserResponse, Error>) -> Void)


enum LoginNavigationOption {
    case signup
    case channel
}

protocol LoginWireframeInterface: WireframeInterface {
    func navigate(to option: LoginNavigationOption)
}

protocol LoginViewInterface: ViewInterface {
}

protocol LoginPresenterInterface: PresenterInterface {
    
    func viewDidLoad()
    func login(with email: String, password: String)
    func signup()
}

protocol LoginInteractorInterface: InteractorInterface {
    func login(with request: LoginRequest, complition: @escaping loginComplition)
    
}
