//
//  LoginViewController.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright © 2021 VDOTOK. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: UIViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var emailTF: UITextField!
    @IBOutlet weak var passwordTF: UITextField!

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        bindPresenter()
    }
    
    @IBAction func didTapLogin(_ sender: UIButton) {
        guard let email = emailTF.text, let password = passwordTF.text else {return}
        presenter.login(with: email, password: password)
    }
    
    @IBAction func didTapSignup(_ sender: UIButton) {
        presenter.signup()
    }
    
    private func bindPresenter() {
        presenter.output = { output in
            switch output {
            case .hideLoading:
                ProgressHud.hide()
            case .showLoading:
                ProgressHud.show(viewController: self)
            case .showError(with: let message):
                ProgressHud.showError(message: message, viewController: self)
            }
        }
    }

}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
    func moveToChat() {
    }
    
}
