//
//  LoginInterfaces.swift
//  IOS-combine
//
//  Created by usama farooq on 30/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

typealias loginComplition = ((Result<UserResponse, Error>) -> Void)


protocol LoginWireframeInterface: WireframeInterface {
}

protocol LoginViewInterface: ViewInterface {
}

protocol LoginPresenterInterface: PresenterInterface {
    
    func viewDidLoad()
    func login(with email: String, password: String)
    
}

protocol LoginInteractorInterface: InteractorInterface {
    func login(with request: LoginRequest, complition: @escaping loginComplition)
}
