//
//  CreateGroupWireframe.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateGroupWireframe: BaseWireframe<CreateGroupViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "CreateGroup", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: CreateGroupViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = CreateGroupInteractor()
        let presenter = CreateGroupPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateGroupWireframe: CreateGroupWireframeInterface {
}
