//
//  CreateGroupViewController.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateGroupViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CreateGroupPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension CreateGroupViewController: CreateGroupViewInterface {
}
