//
//  CreateGroupPresenter.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CreateGroupPresenter {

    // MARK: - Private properties -

    private unowned let view: CreateGroupViewInterface
    private let interactor: CreateGroupInteractorInterface
    private let wireframe: CreateGroupWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: CreateGroupViewInterface,
        interactor: CreateGroupInteractorInterface,
        wireframe: CreateGroupWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CreateGroupPresenter: CreateGroupPresenterInterface {
}
