//
//  CreateGroupWireframe.swift
//  IOS-combine
//
//  Created by usama farooq on 02/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import iOSSDKConnect

final class CreateGroupWireframe: BaseWireframe<CreateGroupViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "CreateGroup", bundle: nil)

    // MARK: - Module setup -

    init(client: ChatClient) {
        let moduleViewController = storyboard.instantiateViewController(ofType: CreateGroupViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = CreateGroupInteractor()
        let presenter = CreateGroupPresenter(view: moduleViewController, interactor: interactor, wireframe: self, client: client)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateGroupWireframe: CreateGroupWireframeInterface {
    func moveToChat(with client: ChatClient, group: Group, user: UserResponse) {
        let frame = ChatWireframe(client: client, group: group, user: user, messages: [], vtokSDK: nil)
        navigationController?.pushWireframe(frame)
    }
    
}
